### ISSUE TITLE
Conflicting functions update and partition-by of clojure.core and honeysql-postgres.helpers 

### ISSUE THREAD

**Issue by codingkarthik** [nilenso/honeysql-postgres#20]
``` WARNING: update already refers to: #'clojure.core/update in namespace: planista.db.utils, being replaced by: #'honeysql.helpers/update ```

``` WARNING: partition-by already refers to: #'clojure.core/partition-by in namespace: planista.db.utils, being replaced by: #'honeysql-postgres.helpers/partition-by ```

I'm not sure if this is an issue.

**Comment by ukriish** [comment]
This is usually fine when you've name spaced the lib.

Not sure if I should rename these. Would have to be a breaking change.

**Comment by lensgolda** [comment]
you can add `(:refer-clojure :exclude [find update partition-by])` after `(:require ...)` section inside `(ns ...)`

**Comment by ukriish** [comment]
closing this issue.

You can either choose to exclude as @lensgolda mentioned or namespace the helpers as `sqlh/update`
