### ISSUE TITLE
Minor README improvement.

### ISSUE THREAD

**Issue by laconiccrafts** [nilenso/honeysql-postgres#22]
It's not clear from the README that one needs to require `honeysql-postgres.helpers` and `honeysql-postgres.format` to make it work. 

Since the example uses :refer :all one is lead into believing that some functions from that namespace is being used instead.

Perhaps it would be beneficial for newcomers for the README to state that one MUST require those namespaces for the lib to work.

Also I think the examples would be more clear if, when requiring their ns, the functions were explicitly refered.

I can make a PR if my suggestions are thought to be useful.

**Comment by ukriish** [comment]
@efraimmgon that makes sense. Will be happy merge in the PR.

**Comment by laconiccrafts** [comment]
#23

**Comment by ukriish** [comment]
closing this as #23 has been merged.
