### ISSUE TITLE
Add if-exists to DROP TABLE

### ISSUE THREAD

**Issue by arichiardi** [nilenso/honeysql-postgres#24]
Hi all!

It's been a while but I have another enhancement coming.

Basically I would like to have:

```
DROP TABLE IF EXISTS t1, t2, t3
```

There is one problem though, the current parameters to `:drop-table` are `[_ tables]`, which means that if I add `[_ if-exists tables]` it will be a breaking change in the API.

What do you folks think about this? How should the api look like?

**Comment by arichiardi** [comment]
Never mind I found the solution and it's not breaking :smile:, see #25

**Comment by ukriish** [comment]
This is something I missed adding and never got around to. 

Will look at the PR, thanks @arichiardi!!
