### ISSUE TITLE
Require the format namespace in the helper

### ISSUE THREAD

**Issue by arichiardi** [nilenso/honeysql-postgres#27]
Hi there!

I found myself including two namespaces, one for the helpers and the other one for the format and questioned "what if the helper required format so that I don't have to remember?"

There must be a reason why we don't do it though so I am opening an issue in order to ask 😉

**Comment by ukriish** [comment]
@arichiardi I've kept it this way to keep this in accordance with how honeysql is written. I didn't want to change much to keep it familiar.

Actually, I think you have a point. That should work. 🤔

**Comment by kitallis** [comment]
This was sorted in the [0.3.104](https://github.com/nilenso/honeysql-postgres/releases/tag/0.3.104) release.

cc @arichiardi
