### ISSUE TITLE
`returning` helper does not handle column aliases properly

### ISSUE THREAD

**Issue by nimaai** [nilenso/honeysql-postgres#37]
Hi

There is a difference in behaviour of `sql/format` applied to hand-written sqlmap and the one produced by the helpers in respect to `returning` and column aliases. The latter produces an invalid SQL string (commas missing).

I have written a test for it: https://github.com/nimaai/honeysql-postgres/commit/b575f98ef8bb13f3ac5660cf40acbc1828bb17c4

Greetings,
Matus

**Comment by scimetfoo** [comment]
We'll look into this. Feel free to raise a PR if you have something already implemented.

**Comment by scimetfoo** [comment]
Apologies for the delayed response. The `defhelper` macro nests the collection provided to the `returning` helper function one level further. That wasn't being accounted for while formatting. This is fixed in https://github.com/nilenso/honeysql-postgres/pull/48

**Comment by p-himik** [comment]
I'm not sure if that was the right call.
As per the original test in the OP, `RETURNING foo, bar baz` is the _right_ thing to do - the comma separates fields, the space between `bar` and `baz` creates an aliaz `baz` for the field `bar`. In the exact same way `select` is working.

But now `flatten` is used, meaning that it's impossible to create aliases in `returning`.
