### ISSUE TITLE
Add name qualifier for OVER / PARTITION BY

### ISSUE THREAD

**Issue by nid90** [nilenso/honeysql-postgres#4]
We would like to be able to do this:

`SELECT id, max(foo) OVER (PARTITION BY bar) AS baz FROM table;`

The way we're currently attempting to write it, is like this:

`(-> (select :id (sql/call :max :foo)) (over (partition-by :bar)) (from :table))`

However, this generates a default column name of `max` which we can use as the name qualifier. But we would like to be able to specify a custom name like `baz` as in the query above.

Is that currently possible in any way? If not let's patch `over` to support this.

**Comment by ukriish** [comment]
Yea, that makes sense. With current implementation you wouldn't be able to do that, also one won't be able to add multiple window functions, which should be allowed. 

Will change the implementation to something like
`(over [aggregator-function window-function alias] ... )` where the `alias` would be optional. 

At the same time providing the option of specifying the window function using the `window` clause and replace the `wndow-function` in the vector with the corresponding window alias, like
`(-> (over [aggregator-function :w]) (window :w window-function))`

Example below 

``` clj
(-> (select :id)
               (over
                [(sql/call :avg :salary) (-> (partition-by :department) (order-by [:designation])) :Average]
                [(sql/call :max :salary) :w :MaxSalary])
               (from :employee)
               (window :w (partition-by :department))
               sql/format)
=> ["SELECT id , avg(salary) OVER (PARTITION BY department ORDER BY designation) AS Average, max(salary) OVER w AS MaxSalary FROM employee WINDOW w AS (PARTITION BY department)"]
```

This would be a breaking change so will release this as updated version and not in the current snapshot.
