### ISSUE TITLE
Release with DISTINCT ON support

### ISSUE THREAD

**Issue by viesti** [nilenso/honeysql-postgres#44]
Hi! Thanks for the nice library, I've been using it quite a lot lately :)

I noticed that DISTINCT ON is [supported now](https://github.com/nilenso/honeysql-postgres/blob/master/src/honeysql_postgres/format.cljc#L224-L225), but it hasn't been released yet (0.2.6 doesn't contain the change). A new release would be neat.

Cheers! :)

**Comment by scimetfoo** [comment]
Hi @viesti. We're prepping for a release. There should be a new version out soon.

**Comment by viesti** [comment]
Thanks for the heads up! :)

**Comment by kitallis** [comment]
Hi @viesti, this is now available in the [0.3.104](https://github.com/nilenso/honeysql-postgres/releases/tag/0.3.104) release.

**Comment by viesti** [comment]
Thank you!
