### ISSUE TITLE
Fix the deprecated usage of unqualified dependency name

### ISSUE THREAD

**Issue by p-himik** [nilenso/honeysql-postgres#52]
Unqualified lib names in `deps.edn` have been deprecated in `tools.deps.alpha` 0.9.745 (since July 22, 2020):
```
DEPRECATED: Libs must be qualified, change honeysql => honeysql/honeysql (/app/.gitlibs/libs/nilenso/honeysql-postgres/cd8c7c3c6f7a1b16fd94a7838bb934fc888ecece/deps.edn
```

**Comment by scimetfoo** [comment]
Hey @p-himik. #46 does away with deps.edn. This change shouldn't be required once that PR is merged.
