### ISSUE TITLE
Format doesn't yield the expected output

### ISSUE THREAD

**Issue by elarous** [nilenso/honeysql-postgres#63]
Thank you very much for this great library 🙏 

This is either an issue or I am just missing something.
When I try to format this:
```clojure
(sql/format
    {:insert-into :single_attrs,
     :values
     [{:id #uuid "0ea136ad-061d-45f1-8d92-db5627a156f2",
       :name "id",
       :mapped_to "uuid",
       :collection "user",
       :schema_id #uuid "e927ad6f-da2b-46a6-9550-c22b3bfcc9ce"}],
     :upsert
     {:on-conflict [:id],
      :do-update-set [:name :mapped_to :collection :schema_id]},
     :returning :*})
```

it yields:
```
[INSERT INTO single_attrs (id, name, mapped_to, collection, schema_id) VALUES (?, ?, ?, ?, ?)   #uuid "0ea136ad-061d-45f1-8d92-db5627a156f2" id uuid user #uuid "e927ad6f-da2b-46a6-9550-c22b3bfcc9ce"]
```

I got the top hash map by using the helper functions in `honeysql` and `honeysql-postgres`:

```clojure
(-> (insert-into :single_attrs)
        (values (vec data))
        (hp/upsert (-> (hp/on-conflict :id)
                       (hp/do-update-set :name :mapped_to :collection :schema_id)))
        (hp/returning :*))
```

I am using `honeysql` version `1.0.444`, and `honeysql-postgres` version `0.2.6`

**Comment by scimetfoo** [comment]
@elarous not importing honeysql-postgres.format can cause this. Could you please check if that's the case and revert.

We've fixed this. From the next release, importing honeylsql-postgres.format won't be necessary.

**Comment by scimetfoo** [comment]
@elarous not importing the honeysql-postgres.format ns can cause this. 

However, we've made a change so that importing honeysql-postgres.format won't be necessary next version onwards.

**Comment by elarous** [comment]
@scimetfoo It works after importing `honeysql-postgres.format`, thank you 🙏 
I'll close the issue
