### ISSUE TITLE
Published jar has odd dependencies since 0.2.5

### ISSUE THREAD

**Issue by frenchy64** [nilenso/honeysql-postgres#66]
According to https://clojars.org/nilenso/honeysql-postgres/versions/0.2.6 there are some strange dependencies that don't seem to be related to this repo:

```
net.cgrand/macrovich 0.2.1    <------
org.clojure/clojure 1.9.0
honeysql 0.9.4
org.clojure/spec.alpha 0.1.143     <------
org.clojure/core.specs.alpha 0.1.24      <------
```

**Comment by kitallis** [comment]
Hi @frenchy64, this is sorted in the new releases [0.3.104](https://clojars.org/nilenso/honeysql-postgres/versions/0.3.104) and [0.4.112](https://clojars.org/nilenso/honeysql-postgres/versions/0.4.112).

**Comment by frenchy64** [comment]
Thanks @kitallis!
