### ISSUE TITLE
[feature request] add support for FILTER and WITHIN GROUP clause for aggregate expressions

### ISSUE THREAD

**Issue by nid90** [nilenso/honeysql-postgres#9]
Description here: https://www.postgresql.org/docs/9.4/static/sql-expressions.html

**Comment by mping** [comment]
Any progress on this?

**Comment by ukriish** [comment]
@mping Sorry, I never go around to this. Will try to get this added soon.

**Comment by mping** [comment]
Sure, np.

**Comment by kitallis** [comment]
This is now available in the in the [0.4.112](https://github.com/nilenso/honeysql-postgres/releases/tag/0.4.112) release.

cc @nid90 @mping

**Comment by mping** [comment]
Great stuff :+1: ty @kitallis
